# Generated by Django 4.1.3 on 2024-12-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('croppedImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
