# Generated by Django 5.1.4 on 2024-12-17 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_registration_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.DateTimeField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('years_of_training', models.IntegerField()),
                ('payment_id', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
