# Generated by Django 5.1.4 on 2024-12-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='years_of_training',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
