# Generated by Django 5.1.4 on 2024-12-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_participant_school_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
