# Generated by Django 5.1.4 on 2024-12-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_participant_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
