# Generated by Django 4.1.3 on 2024-06-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('monthly', models.DecimalField(decimal_places=2, max_digits=7)),
                ('yearly', models.DecimalField(decimal_places=2, max_digits=7)),
                ('extraDetail', models.CharField(max_length=500)),
            ],
        ),
    ]
