# Generated by Django 4.1.3 on 2024-06-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='extraDetail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
