# Generated by Django 4.1.3 on 2024-06-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_training_extradetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='croppedImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
