# Generated by Django 4.1.3 on 2024-06-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_training_croppedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='extraDetail',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='training',
            name='extraDetail',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
