# Generated by Django 4.1.3 on 2024-06-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_membership_extradetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='yearly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
