# Generated by Django 4.1.3 on 2024-07-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_coaches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coaches',
            new_name='Coach',
        ),
    ]
