# Generated by Django 4.1.3 on 2024-07-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_coach_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='stats',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
