# Generated by Django 4.1.3 on 2024-07-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_coach_bio_alter_coach_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='signupFee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='background',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coach',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
