# Generated by Django 4.1.3 on 2024-07-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_membership_deleted_membership_signupfee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='disciple',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='orderNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
