# Generated by Django 4.1.3 on 2024-12-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_coach_disciple_coach_ordernumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('croppedImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='coach',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
