# Generated by Django 4.1.3 on 2024-12-14 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_events_alter_coach_bio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
