# Generated by Django 4.1.3 on 2024-12-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_events_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
